ui
Mino-dev/Notable-OpenCV pull request #10
Opened 2021-02-14 15:44 UTC by jmcroduac

Changed design of fragment_camera and fragment_preview_image buttons

2021-02-15 03:07 UTC, Mino-dev commented on app/build.gradle
> +    implementation "androidx.fragment:fragment:1.3.0-alpha08"
Akala ko di na need to once you include yung fragments for kotlin?

2021-02-15 03:09 UTC, Mino-dev requested changes

2021-02-15 03:09 UTC, Mino-dev commented on app/src/main/java/me/togaparty/notable_opencv/fragments/DashboardFragment.kt
> +                                        to R.id.action_dashboardFragment_to_cameraFragment.toString()))
Ah. May bagong changes ako dito sa upstream siguro paresolve muna

2021-02-15 03:13 UTC, Mino-dev commented on app/src/main/java/me/togaparty/notable_opencv/fragments/DashboardFragment.kt
> +                                        to R.id.action_dashboardFragment_to_cameraFragment.toString()))
https://github.com/Mino-dev/Notable-OpenCV/blob/b3a09cf064c0c7fc31fd15b4702b9eed6515e56e/app/src/main/java/me/togaparty/notable_opencv/fragments/DashboardFragment.kt#L46

2021-02-15 16:23 UTC, jmcroduac commented on app/build.gradle
> +    implementation "androidx.fragment:fragment:1.3.0-alpha08"
Di ko rin alam eh pero may lumalabas kasi na unresolved references dun sa yalantis so dinagdag ko yang line na yan para ma-run ko siya.

2021-02-16 01:39 UTC, Mino-dev approved these changes

2021-02-16 01:39 UTC, merged